# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml"
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)"
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/halotroop2288/mineralsplus-mod/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]]
# The mod's id
modId="mineralsplus"
# The version number of the mod - there's a few well known ${} variables usable here or just hard-code it
version="${file.jarVersion}" #mandatory
 # A display name for the mod
displayName="Minerals+" #mandatory
# A URL for the "home page" for this mod, displayed in the mod UI
displayURL="https://github.com/halotroop2288/mineralsplus-mod"
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="MineralsPlus.png"
# A text field displayed in the mod UI
credits="Made by halotroop2288"
# A text field displayed in the mod UI
authors="halotroop2288"
# The description text for the mod (multi line!) (#mandatory)
description='''
This mod adds all the minerals you could ever think of, in a vein attempt to reduce the amount of mods that add their own minerals and just tend to cause confusion for users.
Instead of adding your own minerals, consider adding this mod as a dependency and using tags in your crafting recipes. :)
If a mineral you want to use is missing, please consider reporting it as an issue, or contributing a pull request for it.
This mod may also be used stand-alone. It adds very minor functionality to all minerals, such as tools, blocks, and ores, so they're not entirely pointless by themselves. (But you really ought to use another mod in conjunction with this.)
'''