package com.github.halotroop2288.materialsplus.init;

import org.apache.commons.lang3.ArrayUtils;

import com.github.halotroop2288.materialsplus.items.QuickItemSet;

import net.minecraft.block.Block;
import net.minecraft.item.Item;

public class MaterialList
{
	private static QuickItemSet	// 					Name					Raw		Block	Ore		Nug/Shard		Plate		Dust	ImpureDust	PurifiedDust
	Actinium 					= new QuickItemSet("actinium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Adamantine 					= new QuickItemSet("adamantine", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Adamantium 					= new QuickItemSet("adamantium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	AdvancedAlloy 				= new QuickItemSet("advanced_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	AlchemicalBrass 			= new QuickItemSet("alchimical_brass",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Alduorite 					= new QuickItemSet("aldourite", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Aluminum 					= new QuickItemSet("aluminum", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	AluminumBrass 				= new QuickItemSet("aluminum_brass",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Amber 						= new QuickItemSet("amber",					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Americium 					= new QuickItemSet("americium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Amethyst 					= new QuickItemSet("amethyst", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Antimony 					= new QuickItemSet("antimony", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Apatite 					= new QuickItemSet("apatite", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Arsenic 					= new QuickItemSet("arsenic", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	AstralSilver 				= new QuickItemSet("astral_silver",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Asul 						= new QuickItemSet("asul",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Barium 						= new QuickItemSet("barium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BaseEssence 				= new QuickItemSet("base_essence", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BatteryAlloy 				= new QuickItemSet("battery_alloy", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BedrockAlloy 				= new QuickItemSet("bedrock_alloy",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Beryllium 					= new QuickItemSet("beryllium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Bismuth 					= new QuickItemSet("bismith",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BlackGranite 				= new QuickItemSet("black_granite",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BlackSteel 					= new QuickItemSet("black_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	BlueAlloy 					= new QuickItemSet("blue_alloy", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Bohrium 					= new QuickItemSet("bohrium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Boron 						= new QuickItemSet("boron",	 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Brass 						= new QuickItemSet("brass", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Bronze 						= new QuickItemSet("bronze", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Cadmium 					= new QuickItemSet("cadmium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Caesium 					= new QuickItemSet("caesium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Calcium 					= new QuickItemSet("calcium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Candium 					= new QuickItemSet("candium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Carbon 						= new QuickItemSet("carbon",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	CastIron 					= new QuickItemSet("cast_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Cerium 						= new QuickItemSet("cerium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	CertusQuartz 				= new QuickItemSet("certus_quartz",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Cesium 						= new QuickItemSet("cesium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Charcoal 					= new QuickItemSet("charcoal",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Chrome 						= new QuickItemSet("chrome",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Coal 						= new QuickItemSet("coal",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Cobalt 						= new QuickItemSet("cobalt", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	CobaltBrass 				= new QuickItemSet("cobalt_brass", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ConductiveIron 				= new QuickItemSet("conductive_iron",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Copernicium 				= new QuickItemSet("copernicium",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Copper 						= new QuickItemSet("copper",				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Cupronickel 				= new QuickItemSet("cupronickel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	DamascusSteel 				= new QuickItemSet("damascus_steel",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	DarkIron 					= new QuickItemSet("dark_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	DarkSteel 					= new QuickItemSet("dark_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Darmstadtium 				= new QuickItemSet("darmstadium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	DeepIron 					= new QuickItemSet("deep_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Desh 						= new QuickItemSet("desh",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Diamond 					= new QuickItemSet("diamond",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Dilithium 					= new QuickItemSet("diluthium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Dubnium 					= new QuickItemSet("dubnium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Duranium 					= new QuickItemSet("duranium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Dysprosium 					= new QuickItemSet("dysprosium",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ElectricalSteel 			= new QuickItemSet("electrical_steel", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Electrum 					= new QuickItemSet("electrum",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Elementium 					= new QuickItemSet("elementium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Emerald 					= new QuickItemSet("emerald",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Enderium 					= new QuickItemSet("enderium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	EnderiumBase 				= new QuickItemSet("enderium_base", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	EndSteel 					= new QuickItemSet("end_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	EnergeticAlloy 				= new QuickItemSet("energetic_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	EnhancedGalgadorianMetal 	= new QuickItemSet("enh_galg_metal", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Erbium 						= new QuickItemSet("erbium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Europium 					= new QuickItemSet("europium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ferramic 					= new QuickItemSet("ferramic", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	FerroboronAlloy 			= new QuickItemSet("ferroboron_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Fiery 						= new QuickItemSet("fiery",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	FierySteel 					= new QuickItemSet("fiery_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	FluxCrystal 				= new QuickItemSet("flux_crystal", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	FluxedElectrum 				= new QuickItemSet("fluxed_electrum",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Force 						= new QuickItemSet("force", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Forcicium 					= new QuickItemSet("forcicium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Forcillium 					= new QuickItemSet("forcillium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Francium 					= new QuickItemSet("francium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Gadolinium 					= new QuickItemSet("gadolinum", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	GalgadorianMetal 			= new QuickItemSet("galg_metal", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Gallium 					= new QuickItemSet("gallium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Garnet 						= new QuickItemSet("garnet",				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Germanium 					= new QuickItemSet("germanium",				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	GildedIron 					= new QuickItemSet("gilded_iron",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Glowstone 					= new QuickItemSet("glowstone", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Gold 						= new QuickItemSet("gold",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Granite 					= new QuickItemSet("granite",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Hafnium 					= new QuickItemSet("hafnium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	HardCarbonAlloy 			= new QuickItemSet("hard_carbon_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Hassium 					= new QuickItemSet("hassium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Heavy 						= new QuickItemSet("heavy",					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Holmium 					= new QuickItemSet("holmium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	HSLASteel 					= new QuickItemSet("hsla_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Indium 						= new QuickItemSet("indium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Inferium 					= new QuickItemSet("inferium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	InfusedGold 				= new QuickItemSet("infused_gold", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Intermedium 				= new QuickItemSet("intermedium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Invar 						= new QuickItemSet("invar",					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Iridium 					= new QuickItemSet("iridium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Iron 						= new QuickItemSet("iron",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ironwood 					= new QuickItemSet("ironwood", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Jasper 						= new QuickItemSet("jasper", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Kanthal 					= new QuickItemSet("kanthal", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Knightmetal 				= new QuickItemSet("knightmetal", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lanthanum 					= new QuickItemSet("lanthanum", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	LapisLazuli 				= new QuickItemSet("lapis", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lazurite 					= new QuickItemSet("lazurite", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lead 						= new QuickItemSet("lead", 					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	LigniteCoal 				= new QuickItemSet("lignite_coal", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lithium 					= new QuickItemSet("lithium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	LithiumManganeseDioxide		= new QuickItemSet("li_manga_dioxide",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lumium 						= new QuickItemSet("lumium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Lutetium 					= new QuickItemSet("lutetium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Magnalium 					= new QuickItemSet("magnalium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Magnesium 					= new QuickItemSet("magnesium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	MagnesiumDiboride 			= new QuickItemSet("magn_diboride",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ManaInfused 				= new QuickItemSet("mana_infused", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Manasteel 					= new QuickItemSet("manasteel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Manganese 					= new QuickItemSet("manganese", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ManganeseDioxide 			= new QuickItemSet("mang_dioxide", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ManganeseOxide 				= new QuickItemSet("mang_oxide", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Manyullyn 					= new QuickItemSet("manyullun", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Meitnerium 					= new QuickItemSet("meitnerium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Mercury 					= new QuickItemSet("mercury", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Metaldiamond				= new QuickItemSet("metaldiamond", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	MeteoricIron				= new QuickItemSet("meteoric_iron",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	MeteoricSteel 				= new QuickItemSet("meteoric_steel",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Midasium 					= new QuickItemSet("midosium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Molybdenum 					= new QuickItemSet("molybdenum", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Monazite 					= new QuickItemSet("monazite",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	MysticIron 					= new QuickItemSet("mystic_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Mythril 					= new QuickItemSet("mythril",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Naquadah 					= new QuickItemSet("naquadah", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	NaquadahAlloy 				= new QuickItemSet("naquadah_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Neodymium 					= new QuickItemSet("neodymium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	NetherStar 					= new QuickItemSet("nether_star", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Neutronium 					= new QuickItemSet("neutronium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Nichrome 					= new QuickItemSet("nichrome", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Nickel 						= new QuickItemSet("nickel",				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Niobium 					= new QuickItemSet("niobium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Niter 						= new QuickItemSet("niter",					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Obsidian 					= new QuickItemSet("obsidian", 				true,	false, 	true, 	true, 			true,		true,		true,	true),
	Olivine 					= new QuickItemSet("olivine",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Opal 						= new QuickItemSet("opal",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Osmiridium 					= new QuickItemSet("osmiridium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Osmium 						= new QuickItemSet("osmium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Palladium 					= new QuickItemSet("palladium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Phosphorus 					= new QuickItemSet("phosphorus", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	PigIron 					= new QuickItemSet("pig_iron", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Plastic 					= new QuickItemSet("plastic",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Platinum 					= new QuickItemSet("platinum",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Plutonium 					= new QuickItemSet("plutonium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Polonium 					= new QuickItemSet("paladium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Potassium 					= new QuickItemSet("potassium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Praseodymium 				= new QuickItemSet("praseodymium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Promethium 					= new QuickItemSet("promethium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Prudentium 					= new QuickItemSet("prudentium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	PulsatingIron 				= new QuickItemSet("pulsating_iron",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Quartz 						= new QuickItemSet("quartz", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Quartzite 					= new QuickItemSet("quartzite", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Radium 						= new QuickItemSet("radium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	RedAlloy 					= new QuickItemSet("red_alloy", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Redstone 					= new QuickItemSet("redstone", 				true,	false, 	true, 	true, 			true,		true,		true,	true),
	RedstoneAlloy 				= new QuickItemSet("redstone_alloy",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	RefinedGlowstone 			= new QuickItemSet("refined_glowstone",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	RefinedIron 				= new QuickItemSet("refined_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	RefinedObsidian 			= new QuickItemSet("refined_obsidian",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ReinforcedMetal 			= new QuickItemSet("reinforced_metal",		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Rhenium 					= new QuickItemSet("rhenium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Rhodium 					= new QuickItemSet("rhodium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Rubber 						= new QuickItemSet("rubber",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Rubidium 					= new QuickItemSet("rubidium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ruby 						= new QuickItemSet("ruby",	 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ruthenium 					= new QuickItemSet("ruthenium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Rutherfordium 				= new QuickItemSet("rutherfordium",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Samarium 					= new QuickItemSet("samarium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Sapphire 					= new QuickItemSet("sapphire",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Scandium 					= new QuickItemSet("scandium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Seaborgium 					= new QuickItemSet("seaborgium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Shadowiron 					= new QuickItemSet("shadowiron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Shadowsteel 				= new QuickItemSet("shadowsteel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Signalum 					= new QuickItemSet("signalum",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Silicon 					= new QuickItemSet("silicon", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Silver 						= new QuickItemSet("silver", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Sodalite 					= new QuickItemSet("sodalite", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Sodium 						= new QuickItemSet("salt",	 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	SolderingAlloy 				= new QuickItemSet("soldering_alloy", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Soularium 					= new QuickItemSet("soularium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Soulsteel 					= new QuickItemSet("soul_steel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	StainlessSteel 				= new QuickItemSet("stainless_steel", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Steel 						= new QuickItemSet("steel", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Steelleaf 					= new QuickItemSet("steelleaf", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Strontium 					= new QuickItemSet("strontium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Sunnarium 					= new QuickItemSet("sunnarium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tantalum 					= new QuickItemSet("tantalum",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tanzanite 					= new QuickItemSet("tanzanite", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Technetium 					= new QuickItemSet("technetium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tellurium 					= new QuickItemSet("tellurium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Terbium 					= new QuickItemSet("terbium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Terrasteel 					= new QuickItemSet("terrasteel", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Thallium 					= new QuickItemSet("thallium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Thaumium 					= new QuickItemSet("thaumium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Thorium 					= new QuickItemSet("thorium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Thulium 					= new QuickItemSet("thulium",	 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tin 						= new QuickItemSet("tin",		 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Titanium 					= new QuickItemSet("titanium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Topaz 						= new QuickItemSet("topaz", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	ToughAlloy 					= new QuickItemSet("tough_alloy", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tritanium 					= new QuickItemSet("tritanium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tungsten 					= new QuickItemSet("tungsten", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Tungstensteel 				= new QuickItemSet("tungstensteel",			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ultimet 					= new QuickItemSet("ultimet", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Umbrium 					= new QuickItemSet("umbrium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Uranium 					= new QuickItemSet("uranium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Vanadium 					= new QuickItemSet("vanadium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Vibrant 					= new QuickItemSet("vibrant", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	VibrantAlloy 				= new QuickItemSet("vibrant_alloy", 		true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Vinteum 					= new QuickItemSet("vinteum", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Wood 						= new QuickItemSet("wood", 					false,	false, 	false, 	true, 			true,		true,		true,	true),
	WroughtIron 				= new QuickItemSet("wrought_iron", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Ytterbium 					= new QuickItemSet("ytterbium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Yttrium 					= new QuickItemSet("yttrium", 				true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Zinc 						= new QuickItemSet("zinc", 					true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Zirconium 					= new QuickItemSet("zirconium", 			true,	true, 	true, 	true, 			true,		true,		true, 	true),
	Zorrasteel 					= new QuickItemSet("zorrasteel", 			false,	true, 	true, 	true, 			true,		true,		true,	true);
	
	public static Item[] allItems()
	{
		Item[] all = (Item[]) ArrayUtils.addAll
		(
				Actinium.QuickMetalSet(),
				Adamantine.QuickGemSet(),
				Adamantium.QuickMetalSet(),
				AdvancedAlloy.QuickMetalSet(),
				AlchemicalBrass.QuickMetalSet(),
				Alduorite.QuickMetalSet(),
				Aluminum.QuickMetalSet(),
				AluminumBrass.QuickMetalSet(),
				Amber.QuickMetalSet(),
				Americium.QuickMetalSet(),
				Amethyst.QuickMetalSet(),
				Antimony.QuickMetalSet(),
				Apatite.QuickMetalSet(),
				Arsenic.QuickMetalSet(),
				AstralSilver.QuickMetalSet(),
				Asul.QuickMetalSet(),
				Barium.QuickMetalSet(),
				BaseEssence.QuickMetalSet(),
				BatteryAlloy.QuickMetalSet(),
				BedrockAlloy.QuickMetalSet(),
				Beryllium.QuickMetalSet(),
				Bismuth.QuickMetalSet(),
				BlackGranite.QuickMetalSet(),
				BlackSteel.QuickMetalSet(),
				BlueAlloy.QuickMetalSet(),
				Bohrium.QuickMetalSet(),
				Boron.QuickMetalSet(),
				Brass.QuickMetalSet(),
				Bronze.QuickMetalSet(),
				Cadmium.QuickMetalSet(),
				Caesium.QuickMetalSet(),
				Calcium.QuickMetalSet(),
				Candium.QuickMetalSet(),
				Carbon.QuickMetalSet(),
				CastIron.QuickMetalSet(),
				Cerium.QuickMetalSet(),
				CertusQuartz.QuickMetalSet(),
				Cesium.QuickMetalSet(),
				Charcoal.QuickMetalSet(),
				Chrome.QuickMetalSet(),
				Coal.QuickMetalSet(),
				Cobalt.QuickMetalSet(),
				CobaltBrass.QuickMetalSet(),
				ConductiveIron.QuickMetalSet(),
				Copernicium.QuickMetalSet(),
				Copper.QuickMetalSet(),
				Cupronickel.QuickMetalSet(),
				DamascusSteel.QuickMetalSet(),
				DarkIron.QuickMetalSet(),
				DarkSteel.QuickMetalSet(),
				Darmstadtium.QuickMetalSet(),
				DeepIron.QuickMetalSet(),
				Desh.QuickMetalSet(),
				Diamond.QuickMetalSet(),
				Dilithium.QuickMetalSet(),
				Dubnium.QuickMetalSet(),
				Duranium.QuickMetalSet(),
				Dysprosium.QuickMetalSet(),
				ElectricalSteel.QuickMetalSet(),
				Electrum.QuickMetalSet(),
				Elementium.QuickMetalSet(),
				Emerald.QuickMetalSet(),
				Enderium.QuickMetalSet(),
				EnderiumBase.QuickMetalSet(),
				EndSteel.QuickMetalSet(),
				EnergeticAlloy.QuickMetalSet(),
				EnhancedGalgadorianMetal.QuickMetalSet(),
				Erbium.QuickMetalSet(),
				Europium.QuickMetalSet(),
				Ferramic.QuickMetalSet(),
				FerroboronAlloy.QuickMetalSet(),
				Fiery.QuickMetalSet(),
				FierySteel.QuickMetalSet(),
				FluxCrystal.QuickMetalSet(),
				FluxedElectrum.QuickMetalSet(),
				Force.QuickMetalSet(),
				Forcicium.QuickMetalSet(),
				Forcillium.QuickMetalSet(),
				Francium.QuickMetalSet(),
				Gadolinium.QuickMetalSet(),
				GalgadorianMetal.QuickMetalSet(),
				Gallium.QuickMetalSet(),
				Garnet.QuickMetalSet(),
				Germanium.QuickMetalSet(),
				GildedIron.QuickMetalSet(),
				Glowstone.QuickMetalSet(),
				Gold.QuickMetalSet(),
				Granite.QuickMetalSet(),
				Hafnium.QuickMetalSet(),
				HardCarbonAlloy.QuickMetalSet(),
				Hassium.QuickMetalSet(),
				Heavy.QuickMetalSet(),
				Holmium.QuickMetalSet(),
				HSLASteel.QuickMetalSet(),
				Indium.QuickMetalSet(),
				Inferium.QuickMetalSet(),
				InfusedGold.QuickMetalSet(),
				Intermedium.QuickMetalSet(),
				Invar.QuickMetalSet(),
				Iridium.QuickMetalSet(),
				Iron.QuickMetalSet(),
				Ironwood.QuickMetalSet(),
				Jasper.QuickMetalSet(),
				Kanthal.QuickMetalSet(),
				Knightmetal.QuickMetalSet(),
				Lanthanum.QuickMetalSet(),
				LapisLazuli.QuickMetalSet(),
				Lazurite.QuickMetalSet(),
				Lead.QuickMetalSet(),
				LigniteCoal.QuickMetalSet(),
				Lithium.QuickMetalSet(),
				LithiumManganeseDioxide.QuickMetalSet(),
				Lumium.QuickMetalSet(),
				Lutetium.QuickMetalSet(),
				Magnalium.QuickMetalSet(),
				Magnesium.QuickMetalSet(),
				MagnesiumDiboride.QuickMetalSet(),
				ManaInfused.QuickMetalSet(),
				Manasteel.QuickMetalSet(),
				Manganese.QuickMetalSet(),
				ManganeseDioxide.QuickMetalSet(),
				ManganeseOxide.QuickMetalSet(),
				Manyullyn.QuickMetalSet(),
				Meitnerium.QuickMetalSet(),
				Mercury.QuickMetalSet(),
				Metaldiamond.QuickMetalSet(),
				MeteoricIron.QuickMetalSet(),
				MeteoricSteel.QuickMetalSet(),
				Midasium.QuickMetalSet(),
				Molybdenum.QuickMetalSet(),
				Monazite.QuickMetalSet(),
				MysticIron.QuickMetalSet(),
				Mythril.QuickMetalSet(),
				Naquadah.QuickMetalSet(),
				NaquadahAlloy.QuickMetalSet(),
				Neodymium.QuickMetalSet(),
				NetherStar.QuickMetalSet(),
				Neutronium.QuickMetalSet(),
				Nichrome.QuickMetalSet(),
				Nickel.QuickMetalSet(),
				Niobium.QuickMetalSet(),
				Niter.QuickMetalSet(),
				Obsidian.QuickMetalSet(),
				Olivine.QuickMetalSet(),
				Opal.QuickMetalSet(),
				Osmiridium.QuickMetalSet(),
				Osmium.QuickMetalSet(),
				Palladium.QuickMetalSet(),
				Phosphorus.QuickMetalSet(),
				PigIron.QuickMetalSet(),
				Plastic.QuickMetalSet(),
				Platinum.QuickMetalSet(),
				Plutonium.QuickMetalSet(),
				Polonium.QuickMetalSet(),
				Potassium.QuickMetalSet(),
				Praseodymium.QuickMetalSet(),
				Promethium.QuickMetalSet(),
				Prudentium.QuickMetalSet(),
				PulsatingIron.QuickMetalSet(),
				Quartz.QuickMetalSet(),
				Quartzite.QuickMetalSet(),
				Radium.QuickMetalSet(),
				RedAlloy.QuickMetalSet(),
				Redstone.QuickMetalSet(),
				RedstoneAlloy.QuickMetalSet(),
				RefinedGlowstone.QuickMetalSet(),
				RefinedIron.QuickMetalSet(),
				RefinedObsidian.QuickMetalSet(),
				ReinforcedMetal.QuickMetalSet(),
				Rhenium.QuickMetalSet(),
				Rhodium.QuickMetalSet(),
				Rubber.QuickMetalSet(),
				Rubidium.QuickMetalSet(),
				Ruby.QuickMetalSet(),
				Ruthenium.QuickMetalSet(),
				Rutherfordium.QuickMetalSet(),
				Samarium.QuickMetalSet(),
				Sapphire.QuickMetalSet(),
				Scandium.QuickMetalSet(),
				Seaborgium.QuickMetalSet(),
				Shadowiron.QuickMetalSet(),
				Shadowsteel.QuickMetalSet(),
				Signalum.QuickMetalSet(),
				Silicon.QuickMetalSet(),
				Silver.QuickMetalSet(),
				Sodalite.QuickMetalSet(),
				Sodium.QuickMetalSet(),
				SolderingAlloy.QuickMetalSet(),
				Soularium.QuickMetalSet(),
				Soulsteel.QuickMetalSet(),
				StainlessSteel.QuickMetalSet(),
				Steel.QuickMetalSet(),
				Steelleaf.QuickMetalSet(),
				Strontium.QuickMetalSet(),
				Sunnarium.QuickMetalSet(),
				Tantalum.QuickMetalSet(),
				Tanzanite.QuickMetalSet(),
				Technetium.QuickMetalSet(),
				Tellurium.QuickMetalSet(),
				Terbium.QuickMetalSet(),
				Terrasteel.QuickMetalSet(),
				Thallium.QuickMetalSet(),
				Thaumium.QuickMetalSet(),
				Thorium.QuickMetalSet(),
				Thulium.QuickMetalSet(),
				Tin.QuickMetalSet(),
				Titanium.QuickMetalSet(),
				Topaz.QuickMetalSet(),
				ToughAlloy.QuickMetalSet(),
				Tritanium.QuickMetalSet(),
				Tungsten.QuickMetalSet(),
				Tungstensteel.QuickMetalSet(),
				Ultimet.QuickMetalSet(),
				Umbrium.QuickMetalSet(),
				Uranium.QuickMetalSet(),
				Vanadium.QuickMetalSet(),
				Vibrant.QuickMetalSet(),
				VibrantAlloy.QuickMetalSet(),
				Vinteum.QuickMetalSet(),
				Wood.QuickMetalSet(),
				WroughtIron.QuickMetalSet(),
				Ytterbium.QuickMetalSet(),
				Yttrium.QuickMetalSet(),
				Zinc.QuickMetalSet(),
				Zirconium.QuickMetalSet(),
				Zorrasteel.QuickMetalSet()
		);
		return (Item[]) all;
	}
	
	public static Block[] allBlocks()
	{
		Block[] all = (Block[]) ArrayUtils.addAll
		(
				Actinium.QuickBlockSet(),
				Adamantine.QuickGemSet(),
				Adamantium.QuickBlockSet(),
				AdvancedAlloy.QuickBlockSet(),
				AlchemicalBrass.QuickBlockSet(),
				Alduorite.QuickBlockSet(),
				Aluminum.QuickBlockSet(),
				AluminumBrass.QuickBlockSet(),
				Amber.QuickBlockSet(),
				Americium.QuickBlockSet(),
				Amethyst.QuickBlockSet(),
				Antimony.QuickBlockSet(),
				Apatite.QuickBlockSet(),
				Arsenic.QuickBlockSet(),
				AstralSilver.QuickBlockSet(),
				Asul.QuickBlockSet(),
				Barium.QuickBlockSet(),
				BaseEssence.QuickBlockSet(),
				BatteryAlloy.QuickBlockSet(),
				BedrockAlloy.QuickBlockSet(),
				Beryllium.QuickBlockSet(),
				Bismuth.QuickBlockSet(),
				BlackGranite.QuickBlockSet(),
				BlackSteel.QuickBlockSet(),
				BlueAlloy.QuickBlockSet(),
				Bohrium.QuickBlockSet(),
				Boron.QuickBlockSet(),
				Brass.QuickBlockSet(),
				Bronze.QuickBlockSet(),
				Cadmium.QuickBlockSet(),
				Caesium.QuickBlockSet(),
				Calcium.QuickBlockSet(),
				Candium.QuickBlockSet(),
				Carbon.QuickBlockSet(),
				CastIron.QuickBlockSet(),
				Cerium.QuickBlockSet(),
				CertusQuartz.QuickBlockSet(),
				Cesium.QuickBlockSet(),
				Charcoal.QuickBlockSet(),
				Chrome.QuickBlockSet(),
				Coal.QuickBlockSet(),
				Cobalt.QuickBlockSet(),
				CobaltBrass.QuickBlockSet(),
				ConductiveIron.QuickBlockSet(),
				Copernicium.QuickBlockSet(),
				Copper.QuickBlockSet(),
				Cupronickel.QuickBlockSet(),
				DamascusSteel.QuickBlockSet(),
				DarkIron.QuickBlockSet(),
				DarkSteel.QuickBlockSet(),
				Darmstadtium.QuickBlockSet(),
				DeepIron.QuickBlockSet(),
				Desh.QuickBlockSet(),
				Diamond.QuickBlockSet(),
				Dilithium.QuickBlockSet(),
				Dubnium.QuickBlockSet(),
				Duranium.QuickBlockSet(),
				Dysprosium.QuickBlockSet(),
				ElectricalSteel.QuickBlockSet(),
				Electrum.QuickBlockSet(),
				Elementium.QuickBlockSet(),
				Emerald.QuickBlockSet(),
				Enderium.QuickBlockSet(),
				EnderiumBase.QuickBlockSet(),
				EndSteel.QuickBlockSet(),
				EnergeticAlloy.QuickBlockSet(),
				EnhancedGalgadorianMetal.QuickBlockSet(),
				Erbium.QuickBlockSet(),
				Europium.QuickBlockSet(),
				Ferramic.QuickBlockSet(),
				FerroboronAlloy.QuickBlockSet(),
				Fiery.QuickBlockSet(),
				FierySteel.QuickBlockSet(),
				FluxCrystal.QuickBlockSet(),
				FluxedElectrum.QuickBlockSet(),
				Force.QuickBlockSet(),
				Forcicium.QuickBlockSet(),
				Forcillium.QuickBlockSet(),
				Francium.QuickBlockSet(),
				Gadolinium.QuickBlockSet(),
				GalgadorianMetal.QuickBlockSet(),
				Gallium.QuickBlockSet(),
				Garnet.QuickBlockSet(),
				Germanium.QuickBlockSet(),
				GildedIron.QuickBlockSet(),
				Glowstone.QuickBlockSet(),
				Gold.QuickBlockSet(),
				Granite.QuickBlockSet(),
				Hafnium.QuickBlockSet(),
				HardCarbonAlloy.QuickBlockSet(),
				Hassium.QuickBlockSet(),
				Heavy.QuickBlockSet(),
				Holmium.QuickBlockSet(),
				HSLASteel.QuickBlockSet(),
				Indium.QuickBlockSet(),
				Inferium.QuickBlockSet(),
				InfusedGold.QuickBlockSet(),
				Intermedium.QuickBlockSet(),
				Invar.QuickBlockSet(),
				Iridium.QuickBlockSet(),
				Iron.QuickBlockSet(),
				Ironwood.QuickBlockSet(),
				Jasper.QuickBlockSet(),
				Kanthal.QuickBlockSet(),
				Knightmetal.QuickBlockSet(),
				Lanthanum.QuickBlockSet(),
				LapisLazuli.QuickBlockSet(),
				Lazurite.QuickBlockSet(),
				Lead.QuickBlockSet(),
				LigniteCoal.QuickBlockSet(),
				Lithium.QuickBlockSet(),
				LithiumManganeseDioxide.QuickBlockSet(),
				Lumium.QuickBlockSet(),
				Lutetium.QuickBlockSet(),
				Magnalium.QuickBlockSet(),
				Magnesium.QuickBlockSet(),
				MagnesiumDiboride.QuickBlockSet(),
				ManaInfused.QuickBlockSet(),
				Manasteel.QuickBlockSet(),
				Manganese.QuickBlockSet(),
				ManganeseDioxide.QuickBlockSet(),
				ManganeseOxide.QuickBlockSet(),
				Manyullyn.QuickBlockSet(),
				Meitnerium.QuickBlockSet(),
				Mercury.QuickBlockSet(),
				Metaldiamond.QuickBlockSet(),
				MeteoricIron.QuickBlockSet(),
				MeteoricSteel.QuickBlockSet(),
				Midasium.QuickBlockSet(),
				Molybdenum.QuickBlockSet(),
				Monazite.QuickBlockSet(),
				MysticIron.QuickBlockSet(),
				Mythril.QuickBlockSet(),
				Naquadah.QuickBlockSet(),
				NaquadahAlloy.QuickBlockSet(),
				Neodymium.QuickBlockSet(),
				NetherStar.QuickBlockSet(),
				Neutronium.QuickBlockSet(),
				Nichrome.QuickBlockSet(),
				Nickel.QuickBlockSet(),
				Niobium.QuickBlockSet(),
				Niter.QuickBlockSet(),
				Obsidian.QuickBlockSet(),
				Olivine.QuickBlockSet(),
				Opal.QuickBlockSet(),
				Osmiridium.QuickBlockSet(),
				Osmium.QuickBlockSet(),
				Palladium.QuickBlockSet(),
				Phosphorus.QuickBlockSet(),
				PigIron.QuickBlockSet(),
				Plastic.QuickBlockSet(),
				Platinum.QuickBlockSet(),
				Plutonium.QuickBlockSet(),
				Polonium.QuickBlockSet(),
				Potassium.QuickBlockSet(),
				Praseodymium.QuickBlockSet(),
				Promethium.QuickBlockSet(),
				Prudentium.QuickBlockSet(),
				PulsatingIron.QuickBlockSet(),
				Quartz.QuickBlockSet(),
				Quartzite.QuickBlockSet(),
				Radium.QuickBlockSet(),
				RedAlloy.QuickBlockSet(),
				Redstone.QuickBlockSet(),
				RedstoneAlloy.QuickBlockSet(),
				RefinedGlowstone.QuickBlockSet(),
				RefinedIron.QuickBlockSet(),
				RefinedObsidian.QuickBlockSet(),
				ReinforcedMetal.QuickBlockSet(),
				Rhenium.QuickBlockSet(),
				Rhodium.QuickBlockSet(),
				Rubber.QuickBlockSet(),
				Rubidium.QuickBlockSet(),
				Ruby.QuickBlockSet(),
				Ruthenium.QuickBlockSet(),
				Rutherfordium.QuickBlockSet(),
				Samarium.QuickBlockSet(),
				Sapphire.QuickBlockSet(),
				Scandium.QuickBlockSet(),
				Seaborgium.QuickBlockSet(),
				Shadowiron.QuickBlockSet(),
				Shadowsteel.QuickBlockSet(),
				Signalum.QuickBlockSet(),
				Silicon.QuickBlockSet(),
				Silver.QuickBlockSet(),
				Sodalite.QuickBlockSet(),
				Sodium.QuickBlockSet(),
				SolderingAlloy.QuickBlockSet(),
				Soularium.QuickBlockSet(),
				Soulsteel.QuickBlockSet(),
				StainlessSteel.QuickBlockSet(),
				Steel.QuickBlockSet(),
				Steelleaf.QuickBlockSet(),
				Strontium.QuickBlockSet(),
				Sunnarium.QuickBlockSet(),
				Tantalum.QuickBlockSet(),
				Tanzanite.QuickBlockSet(),
				Technetium.QuickBlockSet(),
				Tellurium.QuickBlockSet(),
				Terbium.QuickBlockSet(),
				Terrasteel.QuickBlockSet(),
				Thallium.QuickBlockSet(),
				Thaumium.QuickBlockSet(),
				Thorium.QuickBlockSet(),
				Thulium.QuickBlockSet(),
				Tin.QuickBlockSet(),
				Titanium.QuickBlockSet(),
				Topaz.QuickBlockSet(),
				ToughAlloy.QuickBlockSet(),
				Tritanium.QuickBlockSet(),
				Tungsten.QuickBlockSet(),
				Tungstensteel.QuickBlockSet(),
				Ultimet.QuickBlockSet(),
				Umbrium.QuickBlockSet(),
				Uranium.QuickBlockSet(),
				Vanadium.QuickBlockSet(),
				Vibrant.QuickBlockSet(),
				VibrantAlloy.QuickBlockSet(),
				Vinteum.QuickBlockSet(),
				Wood.QuickBlockSet(),
				WroughtIron.QuickBlockSet(),
				Ytterbium.QuickBlockSet(),
				Yttrium.QuickBlockSet(),
				Zinc.QuickBlockSet(),
				Zirconium.QuickBlockSet(),
				Zorrasteel.QuickBlockSet()
		);
		return (Block[]) all;
	}
}
